name: Node CI pipeline

on:
  push:

jobs:
  build:
    name: Build Hono Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: hono-server:latest
          push: false
